### ISSUE TITLE
Supported languages list

### ISSUE THREAD

**Issue by ogencoglu** [google-research/metricx#1]
Thanks for the great work.

Do you have a list of languages or language-pairs the models support?

**Comment by danieldeutsch** [comment]
Thanks for the question. The pre-trained model, mT5, includes data from about 100 different languages https://arxiv.org/pdf/2010.11934.pdf. We fine-tune mT5 on DA data followed by MQM data. Here are the different language pairs that are in our fine-tuning data:

```
cs-en
de-cs
de-en
de-fr
en-cs
en-de
en-et
en-fi
en-gu
en-iu
en-ja
en-kk
en-lt
en-lv
en-pl
en-ru
en-ta
en-tr
en-zh
et-en
fi-en
fr-de
gu-en
iu-en
ja-en
kk-en
km-en
lt-en
lv-en
pl-en
ps-en
ro-en
ru-en
ta-en
tr-en
zh-en
```

Even if the language pair you're interested in is not represented here, there is evidence that learned metrics seem to generalize decently well to unseen language pairs as long as the language was included in the pre-trained model (see https://arxiv.org/pdf/2311.09828.pdf).

**Comment by ogencoglu** [comment]
Thanks for the swift reply!
