### ISSUE TITLE
Query regarding computational resources needed for MetricX 23 QE XXL

### ISSUE THREAD

**Issue by miagrbr-MC** [google-research/metricx#6]
Hello! I would like to first say thank you for making your work available and I apologise in advance if this query has been addressed, I have tried to find this information elsewhere but have been unsuccessful thus far. 

I am trying to use the MetricX 23 QE XXL model (https://huggingface.co/google/metricx-23-qe-xxl-v2p0/tree/main) with the provided predict.py script in this repository. Attempting to load the model weights in a GPU-based environment with 32GB of RAM available results in CUDA running out of memory. 

I would like to kindly ask for some more information regarding the amount of RAM (as well as other general details regarding the environment) required to successfully load the weights as well as use MetricX 23 QE XXL for inference. 

Thank you so much, I appreciate your time :)

**Comment by graftim** [comment]
Hi there. I'm not sure how much memory it consumes exactly. I know I can run the XXL model on 80GB VRAM but not on 48GB, so it must be somewhere in between :)

**Comment by miagrbr-MC** [comment]
> Hi there. I'm not sure how much memory it consumes exactly. I know I can run the XXL model on 80GB VRAM but not on 48GB, so it must be somewhere in between :)

Thank you for your reply! It definitely helps just to know that I'm not doing anything wrong and that 32GB is genuinely not going to cut it. This is going off topic a bit, but have you ever tried doing some model quantization to try get the model to fit into a smaller amount of memory?

**Comment by jjuraska** [comment]
Hi, thank you for your comment! :) We have just released bfloat16 variants of all MetricX-24 models, offering nearly identical performance to their float32 counterparts, but with a 50% smaller memory footprint. We're not planning to do the same for the MetricX-23 models though, so hopefully it won't be an issue for you to switch over to MetricX-24 and make us of its XXL variant!

As for how to estimate how much memory individual models require, you can have a look at the "Files and versions" tab on their respective [Hugging Face pages](https://huggingface.co/collections/google/metricx-24-6745102e7baa7dd7ddf97e04). For example, [metricx-24-hybrid-xxl-v2p6](https://huggingface.co/google/metricx-24-hybrid-xxl-v2p6) needs around 52 GB, while [metricx-24-hybrid-xxl-v2p6-bfloat16](https://huggingface.co/google/metricx-24-hybrid-xxl-v2p6-bfloat16) only needs around 26 GB, so there is a good chance that the latter will fit onto a GPU with 32 GB of memory.

Let us know how it goes or if you have any follow-up questions!

**Comment by miagrbr-MC** [comment]
Thanks so much for sharing this information @jjuraska I am currently in a research phase, so will absolutely be experimenting with all the variants of MetricX-24 as well :)
