### ISSUE TITLE
MetricX24 release

### ISSUE THREAD

**Issue by alvations** [google-research/metricx#8]
Hi, thank you for presenting the paper on https://arxiv.org/abs/2410.03983v1 

Would it be possible to release the model as presented on the paper? Thank you in advance!

**Comment by jjuraska** [comment]
Hi @alvations, we have now added the code for MetricX-24 and you'll find the links to the model checkpoints on Hugging Face in the updated README.

**Comment by alvations** [comment]
Thank you @jjuraska!!
